# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 前端之路
email: yuolsoja@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  把枯燥的技术路线当成一场旅行!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yuolsoja
github_username:  yuolsoja

# Build settings
kramdown:
  input: GFM

#默认固定链接
permalink: 'pretty'

#默认设置
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
